añadido READMI inicial y algunos archivos a docs como guia de go
venrra/apiTreiner pull request #1
Opened 2021-09-17 10:15 UTC by venrra

Se ha creado la rama para el objetivo 0 , y cumplido dicho objetivo.

2021-09-19 15:45 UTC, JJ requested changes
Por favor, dale una vueltecilla para que se pueda aceptar.

2021-09-19 15:45 UTC, JJ commented on README.md
> +Aun no hay nombre oficial pero __una cosa si esta clara__ el proyecto se desarrollara con el lenguaje [`go`](https://golang.org/)
Debes decidir uno de los dos. Y en todo caso, de los dos los que incluyan la palabra "cálculo" será siempre el preferido. Trabajos que se limiten a almacenar cosas y recuperarlas en un UI no van a dar mucho juebo.

El resto de os detalles de aquí en adelante, incluyendo el lenguaje, están fuera del ámbito de este objetivo.

2021-09-19 19:18 UTC, venrra commented on README.md
> +Aun no hay nombre oficial pero __una cosa si esta clara__ el proyecto se desarrollara con el lenguaje [`go`](https://golang.org/)
Okay, ya me he decido. Lo arreglo todo y un nuevo PR

2021-09-20 11:32 UTC, JJ commented on README.md
> +Aun no hay nombre oficial pero __una cosa si esta clara__ el proyecto se desarrollara con el lenguaje [`go`](https://golang.org/)
No hace falta ningún nuevo PR, ni en mi repo, ni en este. Ya me notificará los cambios, yo los miro y/o acepto.

2021-09-21 10:20 UTC, JJ approved these changes
:mechanical_arm:

2021-09-21 12:31 UTC, merged